### ISSUE TITLE
java.net.UnknownHostException while executing (pods/load-pod 'org.babashka/go-sqlite3 "0.0.1")

### ISSUE THREAD

**Issue by mukundzare** [babashka/pod-babashka-go-sqlite3#11]
Trying to load the sqlite3 pod gives me the java.net.UnknownHostException.

----- Error --------------------------------------------------------------------
Type:     java.net.UnknownHostException
Message:  raw.githubusercontent.com
Location: /home/mz/update_env_details.clj:2:1

----- Context ------------------------------------------------------------------
1: (require '[babashka.pods :as pods])
2: (pods/load-pod 'org.babashka/go-sqlite3 "0.0.1")
   ^--- raw.githubusercontent.com
3: (require '[pod.babashka.go-sqlite3 :as sqlite])
.
.
.
----

How can I load the pod locally by manually downloading from github?

**Comment by borkdude** [comment]
@mukundzare You can load the pod locally like this:

```
(pods/load-pod "./the-downloaded-pod")
```
