### ISSUE TITLE
When database path is nil, query and execute! will hang

### ISSUE THREAD

**Issue by judepayne** [babashka/pod-babashka-go-sqlite3#13]
Hi,

Mistakenly setting the database path to `nil`, causes a `query` or an `execute!` statement to hang indefinitely.

    (sqlite\query nil "SELECT * FROM config")

Same for `execute`.
Could we trap this error please?

**Comment by borkdude** [comment]
Hm yeah, I think a PR for this would be good. I can take a look in a few weeks but if someone will beat me to it, I'd be happy to take the PR. cc @lispyclouds
