### ISSUE TITLE
enable fts5

### ISSUE THREAD

**Issue by snewcomer** [babashka/pod-babashka-go-sqlite3#17]
log: `SQLite FTS5 support: {:sqlite_compileoption_used('ENABLE_FTS5') 0}`

```
SELECT sqlite_compileoption_used('ENABLE_FTS5');
```

I'm new to this library so perhaps there is some configuration and tooling.  But how can I get full text search available in the sqlite?  I see this old [comment](https://github.com/mattn/go-sqlite3/issues/465#issuecomment-333304559) in the go-sqlite library.

**Comment by lispyclouds** [comment]
#18 does this, @borkdude should we enable this generally? im adding some tests too
