### ISSUE TITLE
Does not run on Intel mac

### ISSUE THREAD

**Issue by larstvei** [babashka/pod-babashka-go-sqlite3#19]
Hi!

Thank you for this great interface for sqlite3!

I shared a babashka script using this pod to a user running an Intel mac, resulting in the following error:

```
java.io.IOException: Cannot run program "/Users/user/.user/pods/repository/org.babashka/go-sqlite3/0.2.4/mac_os_x/x86_64/pod-babashka-go-sqlite3": error=86, Bad CPU type in executable
```

I found #12, and suggested downgrading `0.1.0`, which worked perfectly. I think maybe the fix for M1 macs broke intel macs? I run an M1 mac myself, so it's hard for me to verify that the issue was introduced by #12, but it is so far my best guess!

**Comment by borkdude** [comment]
I have an Intel mac here as well (as well as an M1) one and can reproduce with 0.2.4. 0.2.3 still works for me.

**Comment by borkdude** [comment]
I found the issue, it turns out that CircleCI silently changed their runner to M1:

https://app.circleci.com/pipelines/github/babashka/pod-babashka-go-sqlite3/117/workflows/39932712-bde5-40ad-b4ff-3e5af189dd9e/jobs/191?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

**Comment by borkdude** [comment]
I thought adding `GOARCH=amd64` to the `go` invocation would fix this problem, but apparently not, with 0.2.5 I still get the same problem. 

@lispyclouds perhaps you can take a look at this go stuff?

**Comment by larstvei** [comment]
I am glad that you were able to get something out of the not-very-informative bug report!

**Comment by borkdude** [comment]
At least you can still use 0.2.3 for now. Will take a look later. In can make a specific intel runner on circle to fix the problem for sure.

**Comment by lispyclouds** [comment]
I will take a closer look soon.

**Comment by lispyclouds** [comment]
Found the issue:
- The build step is correct, it _does_ build the amd64 one as expected
- But, the test [script](https://github.com/babashka/pod-babashka-go-sqlite3/blob/main/script/test) has another build step which doesnt take in that param and overwrites the binary resulting in the amd64 becoming arm64 🤦🏽

**Comment by lispyclouds** [comment]
@borkdude Fix on #21 tested with the produced artifacts as well.

**Comment by borkdude** [comment]
@lispyclouds Now none of the pods work anymore, I get:

```
$ bb examples/go_sqlite3.clj
Downloading pod org.babashka/go-sqlite3 (0.2.6)
Successfully installed pod org.babashka/go-sqlite3 (0.2.6)
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

I'll take a look...

**Comment by lispyclouds** [comment]
Interesting, I'm taking a look as well

**Comment by borkdude** [comment]
Alright, 0.2.7 finally works, tested both on mac intel and arm locally.
